# Generated by Django 6.0.1 on 2026-01-29 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзывы клиента', 'verbose_name_plural': 'Отзывы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='mastertype',
            options={'verbose_name': 'Мастер-Категори', 'verbose_name_plural': 'Мастеры-Категории'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотогалерея работ', 'verbose_name_plural': 'Фотогалерея работы'},
        ),
        migrations.AlterModelOptions(
            name='phototype',
            options={'verbose_name': 'Фотогалерея работ типы', 'verbose_name_plural': 'Фотогалерея работы типы'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'тип-услуг', 'verbose_name_plural': 'типы-услуги'},
        ),
        migrations.AddField(
            model_name='photo',
            name='typename',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.phototype'),
            preserve_default=False,
        ),
    ]
