# Generated by Django 6.0.1 on 2026-01-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_feedback_options_alter_mastertype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='photo',
        ),
    ]
