# Generated by Django 6.0.1 on 2026-01-29 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_feedback_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='typename',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.servicetype'),
            preserve_default=False,
        ),
    ]
