# Generated by Django 6.0.1 on 2026-01-30 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_services_typename'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.master'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='typename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.servicetype'),
        ),
    ]
