# Generated by Django 6.0.1 on 2026-01-30 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_photo_master_alter_services_typename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.mastertype'),
        ),
    ]
