# Generated by Django 6.0.1 on 2026-01-30 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_photo_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='typephoto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.phototype'),
            preserve_default=False,
        ),
    ]
