# Generated by Django 6.0.1 on 2026-01-30 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_master_typephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.master'),
        ),
    ]
