# Generated by Django 6.0.1 on 2026-01-30 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_photo_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услугие-Наращивание ресниц'},
        ),
        migrations.CreateModel(
            name='Servicesone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('name', models.CharField(max_length=100)),
                ('money', models.CharField(max_length=100)),
                ('typename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_one', to='core.servicetype')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услугие-Брови',
            },
        ),
        migrations.CreateModel(
            name='Servicestwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('name', models.CharField(max_length=100)),
                ('money', models.CharField(max_length=100)),
                ('typename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_two', to='core.servicetype')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услугие-Ногтевой сервис',
            },
        ),
    ]
