# Generated by Django 6.0.1 on 2026-01-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_services_options_servicesone_servicestwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='money',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='servicesone',
            name='money',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='servicestwo',
            name='money',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
