# Generated by Django 6.0.1 on 2026-01-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicestwo',
            name='typename',
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услугие'},
        ),
        migrations.DeleteModel(
            name='Servicesone',
        ),
        migrations.DeleteModel(
            name='Servicestwo',
        ),
    ]
