# Generated by Django 6.0.1 on 2026-01-31 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_servicestwo_typename_alter_services_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='typename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicetype'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='typename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicetype'),
        ),
        migrations.RemoveField(
            model_name='master',
            name='typephoto',
        ),
        migrations.DeleteModel(
            name='MasterType',
        ),
        migrations.DeleteModel(
            name='PhotoType',
        ),
    ]
