# Generated by Django 6.0.1 on 2026-02-01 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_master_typename_alter_photo_typename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='typename',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.servicetype'),
            preserve_default=False,
        ),
    ]
