# Generated by Django 6.0.1 on 2026-02-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_booking_typename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='typename',
        ),
        migrations.AddField(
            model_name='feedback',
            name='typename',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.servicetype'),
            preserve_default=False,
        ),
    ]
