# Generated by Django 6.0.1 on 2026-02-02 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_booking_typename_feedback_typename'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.master'),
            preserve_default=False,
        ),
    ]
